---
title: "youRfan (8) : postgreSQL 컨테이너 트러블슈팅"
tags: [Sparta, Docker, postgreSQL]
sidebar:
  nav: categories
permalink: "/categories/sparta/projects/yourfan_8"
---

<div class="article__content" markdown="1">

## 🛠️ 트러블슈팅 (1) : FATAL: password authentication failed for user

### 🤔 진단

```zsh
django.db.utils.OperationalError: connection to server at "db" (172.28.0.4), port 5434 failed: FATAL:  password authentication failed for user "admin"
```

&ensp; 요컨대 '비밀번호가 일치하지 않다'입니다. 우선 제 *.env*와 *settings.py*에서 DB 관련 설정은 다음과 같습니다.

```zsh
# .env
POSTGRES_READY=1
POSTGRES_ENGINE=django.db.backends.postgresql
POSTGRES_NAME=postgres
POSTGRES_USER=admin
POSTGRES_PASSWORD=1q2w3e4r
POSTGRES_HOST=db
POSTGRES_PORT=5434
```

```python
# settings.py
DB_ENGINE = str(os.environ.get("POSTGRES_ENGINE"))
DB_NAME = str(os.environ.get("POSTGRES_NAME"))
DB_USER = str(os.environ.get("POSTGRES_USER"))
DB_PW = str(os.environ.get("POSTGRES_PASSWORD"))
DB_HOST = "db" if str(os.environ.get("POSTGRES_HOST")) == "db" else "localhost"
DB_PORT = str(os.environ.get("POSTGRES_PORT"))
IS_DB_AVAIL = all(
    [
        DB_ENGINE,
        DB_NAME,
        DB_USER,
        DB_PW,
        DB_HOST,
        DB_PORT,
    ]
)

IS_POSTGRES_READY = str(os.environ.get("POSTGRES_READY")) == "1"

if IS_DB_AVAIL and IS_POSTGRES_READY:
    DATABASES = {
        "default": {
            "ENGINE": DB_ENGINE,
            "NAME": DB_NAME,
            "USER": DB_USER,
            "PASSWORD": DB_PW,
            "HOST": DB_HOST,
            "PORT": DB_PORT,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
```

&ensp; *settings.py*가 조금 요란합니다만, 잘못된 부분을 찾을 수 없었습니다. 하지만 postgreSQL 컨테이너를 띄워서 장고와 연결하는 과정에서, 계속해서 위와 같은 오류가 발생했습니다. 오류를 해결하기 위해 여러가지 방법들을 시도해봤습니다. postgreSQL 쉘에 들어가서 새로운 유저를 생성한다든지, 권한을 부여한다든지, 비밀번호를 변경한다든지. 그렇지만 전부 실패했고, 해결 방법을 찾은 결과, 원인은 다른 곳에 있었습니다.

### 🥸 해결

&ensp; 원인은 바로 도커 볼륨이었습니다. 결론적으로 기존의 postgreSQL 볼륨을 삭제하고, 다시 `docker compose up`을 실행하니, 비밀번호 인증 오류가 해결됐습니다. 이에 관해 레퍼런스(https://github.com/cookiecutter/cookiecutter-django/issues/1678#issuecomment-403751269)에서는 다음과 같이 설명하고 있습니다.

> Is it possible that you generate the project more than once? In this scenario you get the error that you mention in your first post here. Here is what happens:

> 1. You generate the project the first time. The .env postgres file is populated with the random password

> 2. You run the docker-compose and the containers are created. The postgres container creates the database based on the .env file credentials

> 3. You "regenerate" the project with the same name, so the postgres .env file is populated with a new random password

> 4. You run docker-compose. Since the names of the containers are the same, docker will try to start them (not create them from scratch i.e. it won't execute the Dockerfile to recreate the database). When this happens, it tries to start the database based on the new credentials which do not match the ones that the database was created with, and you get the error message mentioned in your first post.

> If that is the case, and your object is to start a fresh production environment then you can delete the postgres volume.

&ensp; postgreSQL 컨테이너를 실행하면서 몇 번이고`pull`을 반복했었고, *.env*에서 postgresql 비밀번호도 변경한 적이 있습니다. 하지만 그 과정에서 한 번도 볼륨을 삭제하지 않았었습니다.

<br/>

## 🛠️ 트러블슈팅 (2) : value too long for type character varying(30)

### 🤔 진단

&ensp; 입력값의 글자 수가 필드에 지정된 글자 수보다 클 때 발생하는 오류입니다. 다행히 30글자로 `max_length`가 지정된 필드가 하나밖에 없었기 때문에 금방 찾을 수 있었습니다. `max_length`를 255로 변경했고, 글자 수에 제한이 필요하다면 되도록 프론트에서 한 번 걸러내고, 시리얼라이저에서 두 번 걸러내는 식으로 변경해야겠습니다.

### 🥸 해결

&ensp; `max_length`를 늘려주고, migration 파일들을 전부 제거하고, postgreSQL DB 테이블을 초기화까지 시킨 다음에는 오류가 발생하지 않았습니다.

</div>
