---
title: flowery (3) &#58; 장고 백엔드에 MySQL 연동
tags: [Sparta, Django, MySQL]
sidebar:
  nav: categories
permalink: "/categories/sparta/projects/flowery_3"
---

<div class="article__content" markdown="1">
&ensp; 장고는 기본 DB로 sqlite3를 사용합니다. 앱을 런칭할 것도 아니므로, sqlite3만으로 충분하나, 나중을 기하여 다른 DB와도 연동해보고자 합니다. 장고 백엔드와 MySQL을 연동하기 위해서는 다음 두 가지 프로그램이 필요합니다.

1. 장고 프로젝트
2. MySQL WorkBench

&ensp; MySQL과 연동할 것이므로 MySQL를 구동할 앱이 필요합니다.

---

### (1) 패키지 설치

##### 환경설정

&ensp; 먼저, 장고에 관련 파이썬 패키지를 설치해야 하며, 그 첫 번째는 `mysqlclient`입니다. 이 패키지를 설치하기 전에, 혹여 파이썬과 MySQL을 연동해본 적이 없다면, 터미널에서 다음의 코드를 먼저 실행해야 합니다.

```zsh
sudo apt install mysql-server
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install python3-dev default-libmysqlclient-dev build-essential
```

&ensp; 마지막 명령어를 제외하고는 필수가 아닙니다. 하지만 저는 우분투에 mysql이 설치되어 있지 않았는데다, 설치된 패키지들을 업그레이드 하지 않은 채로는 정상 설치되지 않았었습니다. 그래서 우분투에 mysql-server를 설치하고, 패키지들을 최신으로 업그레이드했습니다.

&ensp; 우분투 환경에서는 위의 코드만 입력하면 됩니다. 윈도우나 맥OS 등 기타 OS 환경에서는 다른 코드를 입력해야 하니, [여기](https://pypi.org/project/mysqlclient/)를 참조하세요.

##### `mysqlclient` 설치

`pip install mysqlclient`
`pip install PyMySQL`

&ensp; 환경 설정을 마쳤다면 `mysqlclient`, `PyMySQL`, 두 패키지를 설치합니다. `PyMySQL`은 특히 맥OS 사용하는 사람들은 꼭 설치해야하는 것 같습니다. 제 팀내에서도 맥OS 사용자들은 이 패키지를 사용하지 않으면 장고와 MySQL이 연동되지 않았는 듯 합니다.

<br/>

### (2) 파이썬 환경설정

##### db.py

&ensp; 먼저, DB 객체를 생성해야 합니다. 이 객체 데이터로 장고가 MySQL과의 연동을 시도합니다. _config_ 폴더에 *db.py*라는 DB용 파이썬 파일을 생성하고 다음의 코드를 입력하여 DB 객체를 생성합니다.

```python
#  db.py

import os
import dotenv

env_file = dotenv.find_dotenv()
dotenv.load_dotenv(env_file)

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "my_db", # 연동할 db 이름
        "USER": os.environ.get("MYSQL_USER"), # mysql 계정 유저네임
        "PASSWORD": os.environ.get("MYSQL_PW"), # mysql 계정 비밀번호
        "HOST": "127.0.0.1",
        "PORT": os.environ.get("MYSQL_PORT"),
    }
}
```

##### settings.py

&ensp; 이제 DB 객체를 *settings.py*에서 `import`합니다. 그리고 *settings.py*의 `DATABASES` 변수에 우리가 생성한 DB 객체를 할당합니다.

```python
from . import db

import pymysql

pymysql.version_info = (1, 4, 3, "final", 0)
pymysql.install_as_MySQLdb()
DATABASES = db.DATABASES
```

##### Migrate

&ensp; 여기까지 했다면 MySQL과 연동하기 위해 장고에서 해야 할 기본 설정은 끝난 것입니다. 이제 변경사항들을 프로젝트에 반영하면 합니다. _migrate_ 명령어를 실행합니다.

```zsh
python manage.py makemigrations
python manage.py migrate
python manage.py runserver
```

&ensp; 아무 문제없이 서버가 실행된다면 그것은 정말 행운입니다. 저는 `python manage.py migrate` 명령어 입력에서 가로막혔었습니다. migrate되지 않고 계속해서 오류가 발생했고, 고군분투한 끝에 서버를 실행시킬 수 있었습니다. (이 지점에서 오류가 발생하고 있다면, 장고에서라기보다 MySQL에서 발생할 오류일 가능성이 큽니다. )

<br/>

### (3) MySQL Trouble Shooting

##### 1. Connection refused

```zsh
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)")
```

&ensp; 제가 마주한 첫 번째 에러입니다. 이 에러는 mysql이 실행되어 있지 않거나, 오작동할 때에 위와 같은 에러가 발생합니다.

&ensp; 하지만 저는 mysql이 잘 실행되어 있었음에도 위의 에러가 발생했었습니다. 다행히 mysql을 재시작하니 위의 에러가 사라졌습니다. 터미널에 다음의 명령어를 입력하여 mysql을 재시작합니다.

```zsh
sudo service mysql restart
```

##### 2. Access Deniend

```zsh
django.db.utils.OperationalError: (1698, "Access denied for user 'root'@'localhost'")
```

&ensp; 그 다음으로는 계정에의 접근이 거부되어 에러가 발생했습니다. 사실 무엇이 원인이었는지는 정확히 모릅니다. 그래서 그냥 해결하기까지의 과정을 설명드리겠습니다.

&ensp; 계정 접근 과정에서 문제가 발생했으므로, 먼저 계정을 확인합니다. 터미널에 아래의 명령어를 입력하여 mysql CLI에 진입합니다. root는 자신의 MySQL 계정명입니다.

```zsh
sudo mysql -u root
```

&ensp; 유저 정보에 관한 데이터는 `mysql`이라는 DB에 저장됩니다. 이 `mysql` DB를 불러오는 명령어를 입력합니다. 그리고 해당 DB에서 `User`와 `plugin` 칼럼을 읽어들입니다. (이하 명령어는 MySQL CLI에 입력해야 하며, 평범한 SQL 퀘리문을 입력해야 합니다.)

```zsh
USE mysql;
SELECT User, plugin FROM mysql.user;
```

&ensp; 다음과 같이 출력되면 정상입니다. 조금씩 다를 수 있습니다.

```zsh
# mysql> SELECT User, Host, plugin FROM mysql.user;
+------------------+-----------------------+
| User             | plugin                |
+------------------+-----------------------+
| debian-sys-maint | caching_sha2_password |
| mysql.infoschema | caching_sha2_password |
| mysql.session    | caching_sha2_password |
| mysql.sys        | caching_sha2_password |
| root             | auth_socket           |
+------------------+-----------------------+
```

&ensp; `User` 칼럼의 `root` 계정과 그 `plugin`을 확인합니다. MySQL에서는 `auth_sockey`이라는 플러그인을 사용하여 사용자를 인증합니다. 그런데 이 플러그인이 장고와 연동할 때 종종 걸림돌이 된다고 합니다. 그럴 때는 이 플러그인을 `mysql_native_password` 플러그인으로 교체해주면 됩니다. 다음의 명령어를 입력하세요.

```zsh
update user set plugin='mysql_native_password' where user='root';
flush privileges;
```

&ensp; `flush privileges;` 명령어로 캐시를 지우고 변경사항을 적용합니다. 그리고 다시 테이블을 출력하여 변경사항이 적용됐는지 확인합니다.

```zsh
# mysql> select user, host, plugin from user;

+------------------+-----------------------+
| user             | plugin                |
+------------------+-----------------------+
| debian-sys-maint | caching_sha2_password |
| mysql.infoschema | caching_sha2_password |
| mysql.session    | caching_sha2_password |
| mysql.sys        | caching_sha2_password |
| root             | mysql_native_password |
+------------------+-----------------------+
```

&ensp; 플러그인이 잘 변경된 것을 확인할 수 있습니다. 다음의 명령어로 MySQL CLI를 빠져나옵니다.

```zsh
exit
```

##### 3. Unknown Database

```zsh
django.db.utils.OperationalError: (1049, "Unknown database 'my_db'")
```

&ensp; 다음으로는 MySQL이 `my_db`라는 DB를 찾지 못해서 에러가 발생했습니다. 여기까지 온 것을 보니 접속까지는 잘 되는 듯 싶습니다.

&ensp; 실제로 해당 DB가 존재하지 않아서 MySQL이 찾지 못하는 것일 수도 있습니다. 저는 로컬에만 MySQLWorkbench가 설치되어 있고, 우분투에는 설치되어 있지 않아서 이 에러가 발생했습니다. 우분투에 MySQLWorkbench를 설치하여 진행할 수도 있지만, 저는 우선 터미널에서 명령어로만 조작했습니다. 우분투의 *mysql-server*에 DB를 생성하기 위해 다음의 명령어를 입력하세요. (MySQL CLI에 진입한 상태여야 합니다.)

```zsh
create database my_db character set utf8mb4 collate utf8mb4_general_ci;
```

&ensp; `haracter set utf8mb4 collate utf8mb4_general_ci`는 장고와의 연동을 위한 옵션입니다. 이제 DB를 생성했으니, 다시 장고로 돌아와 migrate를 진행합니다.

```python
python manage.py makemigrations
python manage.py migrate
```

&ensp; migrate가 정상 진행됐다면 마지막으로 터미널에서 `show tables`를 입력하여 DB 테이블이 잘 생성됐는지 확인합니다.

```zsh
+-----------------------------------+
| Tables_in_ky_db                   |
+-----------------------------------+
| article_article                   |
| article_article_likes             |
| article_comment                   |
| article_photos                    |
| auth_group                        |
| auth_group_permissions            |
| auth_permission                   |
| django_admin_log                  |
| django_content_type               |
| django_migrations                 |
| django_session                    |
| users_customuser                  |
| users_customuser_groups           |
| users_customuser_user_permissions |
+-----------------------------------+
```

&ensp; 오류 없이 잘 진행됩니다.

<br/>

### (4) 결론

&ensp; 저는 여기까지 해서 정상적으로 장고와 MySQL이 연동됐습니다. 이외에도 MySQL과의 연동 과정에서 발생하는 수 많은 에러들이 있습니다만, 위의 것들이 주된 에러인 것 같습니다. 또, MySQLWorkbench를 사용하면 에러가 자주 발생하는 것 같습니다. 차라리 터미널이나 MySQL의 쉘에서 퀘리하는 것이 마음 편할지도 모릅니다.

---

**출처**

[pypi - mysqlclient](https://pypi.org/project/mysqlclient/)

</div>
